[project]
name = "tasy-o"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "pathlib>=1.0.1",
    "pydantic-settings>=2.7.1",
    "uvicorn>=0.34.0",
]
